### ISSUE TITLE
Add support for gradient color

### ISSUE THREAD

**Issue by hariangr** [herodotdigital/SnakeBottomNavigationBar#1]
Can you add support for gradient color for the snake?
<img width="700" alt="Screen Shot 2020-02-20 at 23 33 10" src="https://user-images.githubusercontent.com/18433715/74949927-5db16f80-5439-11ea-8626-3b79a534fcb2.png">

**Comment by GoltVik** [comment]
Thank you for request. Yes, I will add gradient support in new version ;)

**Comment by GoltVik** [comment]
@hariangr in version 0.4.0 you can use gradients by setting  **snakeGradient** or **backgroundGradient**

**Comment by hariangr** [comment]
Thank you so much for implementing my feature request @GoltVik
