### ISSUE TITLE
Height

### ISSUE THREAD

**Issue by Leomhl** [herodotdigital/SnakeBottomNavigationBar#10]
We don't have how to set a height from SnakeNavigationBar. Could you please develop this option? Thanks :)

**Comment by GoltVik** [comment]
@Leomhl SnakeNavigationBar uses the default height of the bottom bar: kBottomNavigationBarHeight. Do you want to change the height of the entire bottom bar or just the snake view?

**Comment by jigarfumakiya** [comment]
I want to change the height of the entire bottom bar @GoltVik.
Any there any option available?

**Comment by GoltVik** [comment]
Hi @jigarfumakiya , you can check out 'feature/height' branch where I added this parameter. Please, let me know if this will enough for your purpose and I will merge this changes.

**Comment by jigarfumakiya** [comment]
Will check @GoltVik 
Thanks!

**Comment by jigarfumakiya** [comment]
Hey @GoltVik 
Thanks! for making that change.
Could you please merge the changes that would be great.
Thanks again.

**Comment by GoltVik** [comment]
Done! Enjoy using this feature :)
