### ISSUE TITLE
Uncompatitble (BottomNavigationItem) for new flutter sdk (>=1.20)

### ISSUE THREAD

**Issue by lau1944** [herodotdigital/SnakeBottomNavigationBar#12]
On the newest version of flutter sdk 
bottomNavgationBarItem does not require 'label' parameter on sdk verison >= 20, so the getter method on bottomNavigationItem in this library is no longer working ...😶

**Comment by GoltVik** [comment]
Thank you @lau1944 for pointing this case. You mean that label is not @requared anymore and without this it library no longer working, right?

**Comment by lau1944** [comment]
> Thank you @lau1944 for pointing this case. You mean that label is not @requared anymore and without this it library no longer working, right? 

You can try the newest flutter >= 1.20 
I think the parameters for bottomNavigationbarItem is different

The 'label' is become 'title'
So the get method for label is not working for the latest SDK version.

It's better for you to test it on the lastest SDK  so you can see more details on this.

**Comment by GoltVik** [comment]
Actually 'title' is deprecated on the latest SDK (tested on Channel stable, 1.22.2):

```
BottomNavigationBarItem({
    @required this.icon,
    @Deprecated(
      'Use "label" instead, as it allows for an improved text-scaling experience. '
      'This feature was deprecated after v1.19.0.'
    )
    this.title,
    this.label,
    Widget activeIcon,
    this.backgroundColor,
  })
```

but yes, 'label' is not @requared. 
new version (0.4.1+2) fixes render issue with empty label

**Comment by lau1944** [comment]
Thx !
