### ISSUE TITLE
Request: Add support for  RTL languages 

### ISSUE THREAD

**Issue by Mohanedy98** [herodotdigital/SnakeBottomNavigationBar#15]
Unfortunately, the navigation bar **doesn't support RTL languages as the snake shape isn't aligned properly.**
I hope it would be fixed as soon as possible as I want to use it in an Arabic language app.
Thanks.

<img src="https://i.imgur.com/9nuR3Lq.png"  height="500" />

**Comment by GoltVik** [comment]
Hello @Mohanedy98, thank you for pointing this issue. Please try version  0.4.1+5. This version fixed snakeView selection for RTL layout

**Comment by Mohanedy98** [comment]
It worked well @GoltVik thanks for the fast response. 
but there's an exception thrown when I'm trying to change the app language from RTL (Arabic) to LTR (English) vice versa in the navigation bar animation.

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building AnimatedPositioned(duration: 200ms, left: 205.7, dirty, dependencies: [_EffectiveTickerMode], state: _AnimatedPositionedState#e4c4c(ticker active, has left)):
'package:flutter/src/animation/tween.dart': Failed assertion: line 258 pos 12: 'begin != null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  SnakeNavigationBar file:///D:/WorkProjects/CallSecure/lib/pages/home_page/container_page.dart:25:34
When the exception was thrown, this was the stack: 
#2      Tween.lerp (package:flutter/src/animation/tween.dart:258:12)
#3      Tween.transform (package:flutter/src/animation/tween.dart:281:12)
#4      Animatable.evaluate (package:flutter/src/animation/tween.dart:54:46)
#5      _AnimatedPositionedState.build (package:flutter/src/widgets/implicit_animations.dart:1114:20)
#6      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
...
====================================================================================================

```

**Comment by GoltVik** [comment]
Hello @Mohanedy98,  like I understand you changing layout direction after click on snake bar item. If yes I think this is not a good idea to do that in that way, its better to wait for snake animation and do that. Because changing the layout will change item positions, animation can't be smooth and this is why you have this exception.
