### ISSUE TITLE
Label Style

### ISSUE THREAD

**Issue by pradyotMobifyi** [herodotdigital/SnakeBottomNavigationBar#16]
Hello thank you for the wonderful widget. I had one requirement to ask for or help in how to do it.
I want to style the lables with different fonts and text size.

Is there a way to do it?

I am trying to achieve this.
![image](https://user-images.githubusercontent.com/75113257/102209917-80949f00-3ef7-11eb-8d31-1161b86e097f.png)

In flutter bottomnavigationbar, we have
TextStyle selectedLabelStyle, TextStyle unselectedLabelStyle property so is there any equivalent property in this library.

**Comment by GoltVik** [comment]
Hi @pradyotMobifyi , unfortunately in this version it's not possible to change fontStyle. Thank you for pointing this out , I will provide this function in weekend ;)

**Comment by pradyotMobifyi** [comment]
Thank you @GoltVik for the reply. Will be waiting for this update.

**Comment by GoltVik** [comment]
Hey @pradyotMobifyi, new release 0.4.2 contains now `selectedLabelStyle` and `unselectedLabelStyle`. Please check this update and let me know if everything works fine ;)

**Comment by pradyotMobifyi** [comment]
Thank you @GoltVik . I checked and its working. Thank you for the update. Will close this now.
