### ISSUE TITLE
Label parameter

### ISSUE THREAD

**Issue by egunes2367** [herodotdigital/SnakeBottomNavigationBar#17]
There is no label parameter in BottomNavigationBarItem, so I can't set a label under the item's icon. But, in your example, there are label parameters which didn't work. My English is bad, I hope I could explain.

**Comment by GoltVik** [comment]
Hello @egunes2367, BottomNavigationBarItem has `label` parameter and `child` will be deprecated after v1.19.0. I can guess that you have outdated Flutter version and this is why you have no this parameter. Which Flutter version do you use?

**Comment by egunes2367** [comment]
I'm sorry, you're right. I haven't done the flutter update. :(
