### ISSUE TITLE
A special effect is highly recommended

### ISSUE THREAD

**Issue by GitHubAsural** [herodotdigital/SnakeBottomNavigationBar#21]
Hey buddy, here is an effect, please add it if you can, it will be welcome.

Picture Url: https://dribbble.com/shots/15082020-BottomNavigationBar

**Comment by GoltVik** [comment]
Hey @GitHubAsural , this is not case for BottomBar itself but for yours imagination :) If you want animate yours widget based on SnakeBarBottomNavigation bar you need to start animation on single item not whole widget.
