### ISSUE TITLE
How to remove space from bottom of navigation bar it is issue only in IOS device working fine in andoid

### ISSUE THREAD

**Issue by radheyjat** [herodotdigital/SnakeBottomNavigationBar#24]
In Android working fine as expected but when run on ios same app it's show some margin on bottom

**Android Screenshoot**
![Screenshot from 2021-07-05 17-46-02](https://user-images.githubusercontent.com/64408910/124470170-e889d480-ddb8-11eb-8051-068f596bc523.png)

**IOS Screenshoot**
![Screenshot from 2021-07-05 17-43-36](https://user-images.githubusercontent.com/64408910/124470033-b4161880-ddb8-11eb-823f-da58ad7ae359.png)

**Comment by GoltVik** [comment]
Hello @radheyjat!
Android works the same in this example but with other navigation :)  This gap is the default navigation handle padding per platform to prevent overlapping. New Android versions have the same handle so it will be the same. 

You can wrap yours NavigationBar into  MediaQuery.removePadding widget to remove this gap:

`MediaQuery.removePadding(
        context: context,
        removeBottom: true,
child:<SnakeNavigationBar>
)`

**Comment by GoltVik** [comment]
@radheyjat, if this solution is satisfying for you, please close this issue ;) Thank you!

**Comment by radheyjat** [comment]
Thanks for solution. apology for delay this solution works for me.
