### ISSUE TITLE
Issue on iPhone nav bar design

### ISSUE THREAD

**Issue by FalguniC** [herodotdigital/SnakeBottomNavigationBar#5]
Hi, I am using this library it is working on android as expected, but on IOS UI goes bad, kindly help how to fix this as its`s not showing as floating, screenshot attached as below.

<img width="512" alt="Screenshot 2020-04-24 at 09 09 30" src="https://user-images.githubusercontent.com/24606544/80173676-35e3b100-860e-11ea-9726-9eab514e3c29.png">

**Comment by bluemoon-i** [comment]
my project have the same problem, could you tell me how you solve this bug
