### ISSUE TITLE
Request: add a width variable for the indicator

### ISSUE THREAD

**Issue by elias97850** [herodotdigital/SnakeBottomNavigationBar#7]

**Comment by GoltVik** [comment]
HI @elias97850 , thank you for request. Can you describe more specific what you want to achieve with this variable and where you want to get it ?

**Comment by Prn-Ice** [comment]
Hi @GoltVik , I'd like to make the indicator look like this
![image](https://user-images.githubusercontent.com/48252841/150096718-10e96373-9bd0-462e-88e5-fdc6d3421232.png)

I believe @elias97850 might want the same thing.

**Comment by GoltVik** [comment]
Well, thank you @Prn-Ice for an explanation. I've added the `height` parameter to SnakeShape, now you can create a custom indicator view with padding what you need. Like this:
`
snakeShape = SnakeShape(
shape: RoundedRectangleBorder(),
            padding: EdgeInsets.only(right: 18),
            height: 3,
          );
`

Those changes are published in version 0.6.0 :)

**Comment by Prn-Ice** [comment]
Wow, thanks a lot
