### ISSUE TITLE
Unselected Icon Color

### ISSUE THREAD

**Issue by lau1944** [herodotdigital/SnakeBottomNavigationBar#8]
I want a custom color for unselected items, i have seen that you set other unselected icons colors to the same as SnakeColors, 
Any solution?

**Comment by GoltVik** [comment]
Hi @lau1944. The design idea for this widget was to have exactly this behaviour. The best UI experience is where we have limited colors count, this is why you can't add another colors.

**Comment by lau1944** [comment]
Thank you for your reply.
I understand your point, but in some cases, flexibility is also important, you don't need to close the opening door. 
Maybe add a parameter with a default value ? It is just a suggestion, you don't have to feel much about it.
My solution to the problem is to rewrite some parts of your code and it should work.

**Comment by GoltVik** [comment]
OK thank you. In the new version, the parameter selectedItemColor has been added  :)
